2025-03-11 13:54:44.391 [info] Extension host with pid 45481 started
2025-03-11 13:54:44.391 [info] Skipping acquiring lock for /home/bartosh/.config/Code - OSS/User/workspaceStorage/2741908bbce287f77e115b64ff454b08.
2025-03-11 13:54:44.392 [info] ExtensionService#_doActivateExtension vscode.ipynb, startup: false, activationEvent: 'onNotebookSerializer:jupyter-notebook'
2025-03-11 13:54:44.417 [info] ExtensionService#_doActivateExtension vscode.git-base, startup: true, activationEvent: '*', root cause: vscode.git
2025-03-11 13:54:44.423 [info] ExtensionService#_doActivateExtension vscode.git, startup: true, activationEvent: '*'
2025-03-11 13:54:44.492 [info] ExtensionService#_doActivateExtension vscode.github, startup: true, activationEvent: '*'
2025-03-11 13:54:44.540 [info] ExtensionService#_doActivateExtension ms-toolsai.jupyter, startup: false, activationEvent: 'onNotebook:jupyter-notebook'
2025-03-11 13:54:44.543 [info] ExtensionService#_doActivateExtension ms-toolsai.vscode-jupyter-cell-tags, startup: false, activationEvent: 'onNotebook:jupyter-notebook'
2025-03-11 13:54:44.546 [info] ExtensionService#_doActivateExtension ms-toolsai.vscode-jupyter-slideshow, startup: false, activationEvent: 'onNotebook:jupyter-notebook'
2025-03-11 13:54:44.579 [info] Eager extensions activated
2025-03-11 13:54:44.862 [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch, startup: false, activationEvent: 'onStartupFinished'
2025-03-11 13:54:44.866 [info] ExtensionService#_doActivateExtension vscode.merge-conflict, startup: false, activationEvent: 'onStartupFinished'
2025-03-11 13:54:44.918 [info] ExtensionService#_doActivateExtension ms-python.python, startup: false, activationEvent: 'api', root cause: ms-toolsai.jupyter
2025-03-11 13:54:45.198 [info] ExtensionService#_doActivateExtension ms-toolsai.jupyter-renderers, startup: false, activationEvent: 'api', root cause: ms-toolsai.jupyter
2025-03-11 13:54:45.215 [info] ExtensionService#_doActivateExtension vscode.emmet, startup: false, activationEvent: 'onLanguage'
2025-03-11 13:54:45.520 [info] ExtensionService#_doActivateExtension ms-python.debugpy, startup: false, activationEvent: 'onLanguage:python'
2025-03-11 13:54:45.649 [error] Activating extension ms-python.debugpy failed due to an error:
2025-03-11 13:54:45.649 [error] Error: Extension 'ms-python.debugpy' CANNOT use API proposal: portsAttributes.
Its package.json#enabledApiProposals-property declares:  but NOT portsAttributes.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api ms-python.debugpy
	at N (file:///usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:110:16858)
	at Object.registerPortAttributesProvider (file:///usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:172:55654)
	at t.registerDebugger (/home/bartosh/.vscode-oss/extensions/ms-python.debugpy-2025.0.1-linux-x64/dist/extension.js:2:846258)
	at e.activate (/home/bartosh/.vscode-oss/extensions/ms-python.debugpy-2025.0.1-linux-x64/dist/extension.js:2:1097551)
	at Ow.kb (file:///usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:116:15214)
	at Ow.jb (file:///usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:116:14921)
	at file:///usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:116:13079
	at async aw.n (file:///usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:112:4447)
	at async aw.m (file:///usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:112:4410)
	at async aw.l (file:///usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:112:3866)
2025-03-11 13:54:46.709 [error] Error: Extension 'ms-python.python' CANNOT use API proposal: testObserver.
Its package.json#enabledApiProposals-property declares:  but NOT testObserver.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api ms-python.python
	at N (file:///usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:110:16858)
	at get testResults (file:///usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:172:39426)
	at C.activate (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.0.0-universal/out/client/extension.js:2:908459)
	at /home/bartosh/.vscode-oss/extensions/ms-python.python-2025.0.0-universal/out/client/extension.js:2:2457
	at Array.map (<anonymous>)
	at v.activateWorkspace (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.0.0-universal/out/client/extension.js:2:2447)
2025-03-11 14:30:11.475 [info] ExtensionService#_doActivateExtension vscode.configuration-editing, startup: false, activationEvent: 'onLanguage:jsonc'
2025-03-11 14:30:11.492 [info] ExtensionService#_doActivateExtension vscode.json-language-features, startup: false, activationEvent: 'onLanguage:jsonc'
2025-03-11 14:30:11.601 [info] ExtensionService#_doActivateExtension vscode.typescript-language-features, startup: false, activationEvent: 'onLanguage:jsonc'
2025-03-11 14:47:31.344 [error] [ms-python.python] provider FAILED
2025-03-11 14:47:31.344 [error] Error: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
	at ae (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.0.0-universal/out/client/extension.js:2:1973990)
	at oe (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.0.0-universal/out/client/extension.js:2:1971950)
	at Immediate.<anonymous> (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.0.0-universal/out/client/extension.js:2:1968244)
	at process.processImmediate (node:internal/timers:483:21)
2025-03-11 15:06:58.670 [info] ExtensionService#_doActivateExtension vscode.extension-editing, startup: false, activationEvent: 'onLanguage:markdown'
2025-03-11 15:06:58.690 [info] ExtensionService#_doActivateExtension vscode.markdown-language-features, startup: false, activationEvent: 'onLanguage:markdown'
2025-03-11 15:06:59.247 [info] ExtensionService#_doActivateExtension vscode.markdown-math, startup: false, activationEvent: 'api', root cause: vscode.markdown-language-features
2025-03-11 15:20:43.841 [error] [ms-python.python] provider FAILED
2025-03-11 15:20:43.841 [error] Error: UnboundLocalError: cannot access local variable 'end_index' where it is not associated with a value
	at ae (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.0.0-universal/out/client/extension.js:2:1973990)
	at oe (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.0.0-universal/out/client/extension.js:2:1971950)
	at Immediate.<anonymous> (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.0.0-universal/out/client/extension.js:2:1968244)
	at process.processImmediate (node:internal/timers:483:21)
2025-03-11 15:20:51.147 [error] [ms-python.python] provider FAILED
2025-03-11 15:20:51.147 [error] Error: UnboundLocalError: cannot access local variable 'end_index' where it is not associated with a value
	at ae (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.0.0-universal/out/client/extension.js:2:1973990)
	at oe (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.0.0-universal/out/client/extension.js:2:1971950)
	at Immediate.<anonymous> (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.0.0-universal/out/client/extension.js:2:1968244)
	at process.processImmediate (node:internal/timers:483:21)
2025-03-11 15:23:22.990 [error] [ms-python.python] provider FAILED
2025-03-11 15:23:22.990 [error] Error: UnboundLocalError: cannot access local variable 'end_index' where it is not associated with a value
	at ae (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.0.0-universal/out/client/extension.js:2:1973990)
	at oe (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.0.0-universal/out/client/extension.js:2:1971950)
	at Immediate.<anonymous> (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.0.0-universal/out/client/extension.js:2:1968244)
	at process.processImmediate (node:internal/timers:483:21)
2025-03-11 15:34:45.589 [error] [ms-python.python] provider FAILED
2025-03-11 15:34:45.589 [error] Error: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
	at ae (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.0.0-universal/out/client/extension.js:2:1973990)
	at oe (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.0.0-universal/out/client/extension.js:2:1971950)
	at Immediate.<anonymous> (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.0.0-universal/out/client/extension.js:2:1968244)
	at process.processImmediate (node:internal/timers:483:21)
2025-03-11 15:39:32.226 [error] [ms-python.python] provider FAILED
2025-03-11 15:39:32.226 [error] Error: UnboundLocalError: cannot access local variable 'end_index' where it is not associated with a value
	at ae (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.0.0-universal/out/client/extension.js:2:1973990)
	at oe (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.0.0-universal/out/client/extension.js:2:1971950)
	at Immediate.<anonymous> (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.0.0-universal/out/client/extension.js:2:1968244)
	at process.processImmediate (node:internal/timers:483:21)
2025-03-11 15:48:59.744 [error] [ms-python.python] provider FAILED
2025-03-11 15:48:59.744 [error] Error: UnboundLocalError: cannot access local variable 'end_index' where it is not associated with a value
	at ae (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.0.0-universal/out/client/extension.js:2:1973990)
	at oe (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.0.0-universal/out/client/extension.js:2:1971950)
	at Immediate.<anonymous> (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.0.0-universal/out/client/extension.js:2:1968244)
	at process.processImmediate (node:internal/timers:483:21)
2025-03-11 15:49:54.957 [error] [ms-python.python] provider FAILED
2025-03-11 15:49:54.957 [error] Error: UnboundLocalError: cannot access local variable 'end_index' where it is not associated with a value
	at ae (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.0.0-universal/out/client/extension.js:2:1973990)
	at oe (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.0.0-universal/out/client/extension.js:2:1971950)
	at Immediate.<anonymous> (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.0.0-universal/out/client/extension.js:2:1968244)
	at process.processImmediate (node:internal/timers:483:21)
2025-03-11 15:52:29.210 [error] [ms-python.python] provider FAILED
2025-03-11 15:52:29.210 [error] Error: UnboundLocalError: cannot access local variable 'end_index' where it is not associated with a value
	at ae (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.0.0-universal/out/client/extension.js:2:1973990)
	at oe (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.0.0-universal/out/client/extension.js:2:1971950)
	at Immediate.<anonymous> (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.0.0-universal/out/client/extension.js:2:1968244)
	at process.processImmediate (node:internal/timers:483:21)
2025-03-11 15:54:50.618 [error] [ms-python.python] provider FAILED
2025-03-11 15:54:50.618 [error] Error: UnboundLocalError: cannot access local variable 'end_index' where it is not associated with a value
	at ae (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.0.0-universal/out/client/extension.js:2:1973990)
	at oe (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.0.0-universal/out/client/extension.js:2:1971950)
	at Immediate.<anonymous> (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.0.0-universal/out/client/extension.js:2:1968244)
	at process.processImmediate (node:internal/timers:483:21)
2025-03-12 12:54:13.536 [info] Extension host terminating: renderer closed the MessagePort
2025-03-12 12:54:13.566 [error] Canceled: Canceled
	at new XR (file:///usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:29:110406)
	at Uy.U (file:///usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:29:115016)
	at s.<computed>.n.charCodeAt.s.<computed> (file:///usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:29:112510)
	at mw.g (file:///usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:112:32221)
	at mw.executeCommand (file:///usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:112:31725)
	at r.registerCommand.description (file:///usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:112:31055)
	at mw.h (file:///usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:112:32741)
	at mw.g (file:///usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:112:31818)
	at mw.executeCommand (file:///usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:112:31725)
	at Object.executeCommand (file:///usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:172:37254)
	at ir.set (/home/bartosh/.vscode-oss/extensions/ms-toolsai.jupyter-2025.1.0-universal/dist/extension.node.js:304:165658)
	at dI.updateContextOfActiveNotebookKernel (/home/bartosh/.vscode-oss/extensions/ms-toolsai.jupyter-2025.1.0-universal/dist/extension.node.js:382:11182)
	at dI.onDidKernelStatusChange (/home/bartosh/.vscode-oss/extensions/ms-toolsai.jupyter-2025.1.0-universal/dist/extension.node.js:382:12834)
	at D.B (file:///usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:27:2373)
	at D.C (file:///usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:27:2443)
	at D.fire (file:///usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:27:2660)
	at Cy.<anonymous> (/home/bartosh/.vscode-oss/extensions/ms-toolsai.jupyter-2025.1.0-universal/dist/extension.node.js:299:2959)
	at D.B (file:///usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:27:2373)
	at D.C (file:///usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:27:2443)
	at D.fire (file:///usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:27:2660)
	at e (/home/bartosh/.vscode-oss/extensions/ms-toolsai.jupyter-2025.1.0-universal/dist/extension.node.js:285:32519)
	at I_.dispose (/home/bartosh/.vscode-oss/extensions/ms-toolsai.jupyter-2025.1.0-universal/dist/extension.node.js:285:32642)
	at /home/bartosh/.vscode-oss/extensions/ms-toolsai.jupyter-2025.1.0-universal/dist/extension.node.js:183:1926
	at Array.map (<anonymous>)
	at Pg.dispose (/home/bartosh/.vscode-oss/extensions/ms-toolsai.jupyter-2025.1.0-universal/dist/extension.node.js:183:1917)
	at Object.bhe (/home/bartosh/.vscode-oss/extensions/ms-toolsai.jupyter-2025.1.0-universal/dist/extension.node.js:445:3865)
	at Object.m (/home/bartosh/.vscode-oss/extensions/ms-toolsai.jupyter-2025.1.0-universal/dist/extension.node.proxy.js:1:963)
	at PW.eb (file:///usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:116:11724)
	at file:///usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:116:9874
	at Array.map (<anonymous>)
	at PW.$ (file:///usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:116:9862)
	at PW.terminate (file:///usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:116:10105)
	at wC.terminate (file:///usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:117:1434)
	at ts (file:///usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:190:15080)
	at MessagePortMain.<anonymous> (file:///usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:190:11628)
	at MessagePortMain.emit (node:events:518:28)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:2949) setContext undefined
2025-03-12 12:54:13.571 [info] Extension host with pid 45481 exiting with code 0
